name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:       

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Curl to keep Render service awake
        run: curl -s https://jp-training-backend.onrender.com > /dev/null
