name: Keep Render Alive

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch:       # Allow manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Curl to keep Render service awake
        run: curl -s https://jp-training-backend.onrender.com > /dev/null
